"""VLR.gg API client and helpers (pure, no Discord dependency)."""

from features.vlrgg.client import (
    CACHE_TTL,
    ROUND_ABBREVIATIONS,
    VLRGG_API_URL,
    _clean_vlr_text,
    check_api_health,
    enrich_match_from_details,
    expand_round_name,
    extract_match_id_from_url,
    fetch_all_team_data,
    fetch_live_matches,
    fetch_match_details,
    fetch_team_info,
    fetch_team_matches_by_id,
    fetch_upcoming_matches,
    filter_team_matches,
    format_vlr_date,
    normalize_team_match,
    parse_vlrgg_timestamp,
    vlrgg_request,
)

__all__ = [
    "CACHE_TTL",
    "ROUND_ABBREVIATIONS",
    "VLRGG_API_URL",
    "_clean_vlr_text",
    "check_api_health",
    "enrich_match_from_details",
    "expand_round_name",
    "extract_match_id_from_url",
    "fetch_all_team_data",
    "fetch_live_matches",
    "fetch_match_details",
    "fetch_team_info",
    "fetch_team_matches_by_id",
    "fetch_upcoming_matches",
    "filter_team_matches",
    "format_vlr_date",
    "normalize_team_match",
    "parse_vlrgg_timestamp",
    "vlrgg_request",
]
