"""Unit tests for ``features.rss.parser``."""

import pytest

from features.rss.parser import parse_feed, strip_html
from src.core.errors import IntegrationError

RSS_SAMPLE = """\
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>Free Games Weekly</title>
    <link>https://example.com</link>
    <description>Test feed</description>
    <item>
      <title>Free Game: <b>Frostpunk</b></title>
      <link>https://example.com/frostpunk</link>
      <guid>fg-001</guid>
      <pubDate>Fri, 24 Apr 2026 10:00:00 +0000</pubDate>
      <description>Grab &lt;i&gt;Frostpunk&lt;/i&gt; on Epic until Friday.</description>
    </item>
    <item>
      <title>Free Game: Death Stranding</title>
      <link>https://example.com/ds</link>
      <guid>fg-002</guid>
    </item>
  </channel>
</rss>
"""

ATOM_SAMPLE = """\
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Subreddit r/example</title>
  <link href="https://example.com"/>
  <updated>2026-04-25T10:00:00Z</updated>
  <id>tag:example.com</id>
  <entry>
    <title>Hello there</title>
    <link href="https://example.com/post/1"/>
    <id>tag:example.com,2026:post-1</id>
    <updated>2026-04-25T09:00:00Z</updated>
    <author><name>op</name></author>
    <summary>A nice post.</summary>
  </entry>
</feed>
"""


def test_parse_rss_extracts_two_entries() -> None:
    entries = parse_feed(RSS_SAMPLE)
    assert len(entries) == 2
    assert entries[0].entry_id == "fg-001"
    assert entries[0].title == "Free Game: Frostpunk"
    assert entries[0].link == "https://example.com/frostpunk"
    assert "Frostpunk" in entries[0].summary
    assert entries[0].published is not None


def test_parse_atom_extracts_author_and_summary() -> None:
    entries = parse_feed(ATOM_SAMPLE)
    assert len(entries) == 1
    entry = entries[0]
    assert entry.entry_id == "tag:example.com,2026:post-1"
    assert entry.title == "Hello there"
    assert entry.author == "op"
    assert entry.summary == "A nice post."


def test_strip_html_decodes_entities_and_truncates() -> None:
    out = strip_html("<p>Hello &amp; <i>world</i></p>", max_length=80)
    assert out == "Hello & world"
    long = "x" * 1000
    out = strip_html(long, max_length=20)
    assert len(out) == 20
    assert out.endswith("…")


def test_strip_html_handles_none_and_empty() -> None:
    assert strip_html(None) == ""
    assert strip_html("") == ""
    assert strip_html("   ") == ""


def test_strip_html_preserves_block_boundaries_and_bolds_labels() -> None:
    # LootScraper-style XHTML: each <li>/<p> becomes its own line, and the
    # <b> labels render as Discord markdown bold.
    raw = (
        "<ul>"
        "<li><b>Offer valid from:</b> 2026-05-28 16:02</li>"
        "<li><b>Offer valid to:</b> 2026-06-03 16:00</li>"
        "<p>About the game (<b>Drift86</b>):</p>"
        "</ul>"
    )
    out = strip_html(raw, max_length=400)
    lines = out.split("\n")
    assert "**Offer valid from:** 2026-05-28 16:02" in lines
    assert "**Offer valid to:** 2026-06-03 16:00" in lines
    assert "About the game (**Drift86**):" in lines


def test_strip_html_breaks_on_br_tags() -> None:
    out = strip_html("line one<br>line two<br/>line three", max_length=80)
    assert out == "line one\nline two\nline three"


def test_strip_html_converts_anchors_to_markdown_links() -> None:
    raw = 'Claim it now on <a href="https://store.example.com/app/1">Steam</a>.'
    out = strip_html(raw, max_length=200)
    assert out == "Claim it now on [Steam](https://store.example.com/app/1)."


def test_strip_html_drops_small_fine_print() -> None:
    raw = "<p>Main content here.</p><p><small>Source: Steam, Generated by LootScraper</small></p>"
    out = strip_html(raw, max_length=200)
    assert "Source" not in out
    assert "LootScraper" not in out
    assert out == "Main content here."


def test_parse_feed_raises_on_garbage() -> None:
    with pytest.raises(IntegrationError):
        parse_feed("this is not xml")


def test_parse_feed_raises_on_unknown_root() -> None:
    with pytest.raises(IntegrationError):
        parse_feed("<html><body>nope</body></html>")


RSS_WITH_ENCLOSURE = """\
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <item>
      <title>Free Game</title>
      <link>https://example.com/g</link>
      <guid>g-1</guid>
      <enclosure url="https://example.com/cover.jpg" type="image/jpeg" length="12345"/>
    </item>
  </channel>
</rss>
"""

RSS_WITH_IMG_IN_DESCRIPTION = """\
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <item>
      <title>Free Game</title>
      <link>https://example.com/g</link>
      <guid>g-2</guid>
      <description>&lt;p&gt;Get it now! &lt;img src="https://cdn.example.com/key-art.png" alt="cover"/&gt;&lt;/p&gt;</description>
    </item>
  </channel>
</rss>
"""

ATOM_WITH_MEDIA_THUMBNAIL = """\
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
  <id>tag:example.com</id>
  <entry>
    <title>Post</title>
    <link href="https://example.com/post/1"/>
    <id>tag:1</id>
    <media:thumbnail url="https://example.com/thumb.jpg"/>
  </entry>
</feed>
"""


def test_image_url_from_rss_enclosure() -> None:
    [entry] = parse_feed(RSS_WITH_ENCLOSURE)
    assert entry.image_url == "https://example.com/cover.jpg"


def test_image_url_from_html_description() -> None:
    [entry] = parse_feed(RSS_WITH_IMG_IN_DESCRIPTION)
    assert entry.image_url == "https://cdn.example.com/key-art.png"


def test_image_url_from_atom_media_thumbnail() -> None:
    [entry] = parse_feed(ATOM_WITH_MEDIA_THUMBNAIL)
    assert entry.image_url == "https://example.com/thumb.jpg"


def test_image_url_empty_when_no_image() -> None:
    [entry] = parse_feed(ATOM_SAMPLE)
    assert entry.image_url == ""
