"""Generate ``config.example.json`` from the Web UI schema registry.

``config/`` is gitignored, so the config shape only exists in code — this
script materializes it. Every extension is imported (best-effort) so its
``@register_module`` / ``@register_section`` schemas land in the registry,
then a skeleton is emitted: declared defaults where available, otherwise an
empty value matching the field type.

Usage::

    python scripts/generate_config_example.py            # writes config.example.json
    python scripts/generate_config_example.py --stdout   # prints instead
"""

from __future__ import annotations

import importlib
import json
import os
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

OUTPUT = Path(__file__).resolve().parent.parent / "config.example.json"

# Empty value per widget type when the schema declares no default.
_TYPE_PLACEHOLDERS: dict[str, Any] = {
    "string": "",
    "secret": "",
    "url": "",
    "channel": "",
    "role": "",
    "message": "",
    "number": 0,
    "boolean": False,
    "list": [],
    "list:number": [],
    "messagelist": [],
    "embedlist": [],
    "teams": [],
    "models": [],
    "dict": {},
    "keyvaluemap": {},
    "spotifymap": {},
    "streamermap": {},
    "youtubechannelmap": {},
    "rssfeedmap": {},
    "discord2name": {},
}


def _import_extensions() -> list[str]:
    """Import every extension entry so schemas register; return the failures."""
    failures: list[str] = []
    for entry in sorted(os.listdir("extensions")):
        if entry.startswith("__"):
            continue
        if entry.endswith(".py"):
            module = f"extensions.{entry[:-3]}"
        elif os.path.isfile(os.path.join("extensions", entry, "__init__.py")):
            module = f"extensions.{entry}"
        else:
            continue
        try:
            importlib.import_module(module)
        except Exception as e:  # noqa: BLE001 — a broken extension must not block the rest
            failures.append(f"{module}: {e}")
    return failures


def _field_value(meta: dict[str, Any]) -> Any:
    if "default" in meta:
        return meta["default"]
    return _TYPE_PLACEHOLDERS.get(meta.get("type", "string"), "")


def _skeleton_from_fields(fields: dict[str, dict[str, Any]]) -> dict[str, Any]:
    return {name: _field_value(meta) for name, meta in fields.items() if not meta.get("hidden")}


def build_example() -> dict[str, Any]:
    failures = _import_extensions()
    for failure in failures:
        print(f"warning: skipped {failure}", file=sys.stderr)

    from src.webui import schemas as schemas_module

    global_sections = {
        key: _skeleton_from_fields(schema.get("fields", {}))
        for key, schema in sorted(schemas_module.GLOBAL_CONFIG_SCHEMAS.items())
    }

    modules: dict[str, Any] = {}
    for key, schema in sorted(schemas_module.MODULE_SCHEMAS.items()):
        if schema.get("directValue"):
            modules[key] = {}
            continue
        skeleton = _skeleton_from_fields(schema.get("fields", {}))
        skeleton.setdefault("enabled", False)
        modules[key] = skeleton

    return {
        "_readme": [
            "Skeleton generated by scripts/generate_config_example.py — do not edit by hand.",
            "Copy to config/config.json, fill in the secrets, and replace YOUR_SERVER_ID",
            "with your guild id. Most settings are editable from the Web UI afterwards.",
        ],
        "config": global_sections,
        "servers": {"YOUR_SERVER_ID": modules},
    }


def main() -> None:
    example = build_example()
    payload = json.dumps(example, indent=4, ensure_ascii=False) + "\n"
    if "--stdout" in sys.argv:
        sys.stdout.write(payload)
        return
    OUTPUT.write_text(payload, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
